bugfix: fixed shift operation in modint and simplifications
Two things:
- in the expression simplification engine, left and right shifts are
  performed with a limitless counter. in order to prevent python from
  raising an overflow error, the shift counter must be restricted to
  a plausible range of values. this modification is implemented
  directly into the modint module.
- in the expression simplification engine, arithmetic right shift is
  performed with a potentially negative counter. as it makes little
  sense, the counter parameter is not converted to a signed modint,
  and is used as is.

This modification solves the following failing test (amongst others):

>>> from miasm2.expression.modint import uint64
>>> uint64(1) << uint64(0xFFFFFFFFFFFFFFFF)
OverflowError: long int too large to convert to int
>>> uint64(1) >> uint64(0xFFFFFFFFFFFFFFFF)
OverflowError: long int too large to convert to int